export class Card {
  currency?					: string;		
  cardholder?				: string;		
  cardNumber?				: string;		
  expiryMonth				: string;		
  expiryYear				: string;		
  CV2								: string;		
  cardType					: string;		
  billingSurname		: string;		
  billingFirstNames	: string;		
  billingAddress1		: string;		
  billingAddress2?	: string;		
  billingCity				: string;		
  billingPostcode		: string;		
  billingCountry		: string;		
  billingState      : string;    
  type?             : string;    
  cardHolderName?   : string;    
  lastFourDigits?   : string;    
  id?               : string;		
};